== Using Hyperledger Fabric to deploy smart-contracts
:page-navtitle: HLF Multi-node deployment and use
:page-root: ../../../../
:page-category: Blockchain
:toc:
:data-uri: true
:allow-uri-read: true

Now lets deploy our smart-contracts (chaincode) in the Blockchain.
Go to the directory ~/hyperledger_ws/chaincode_examples/example1/.
In this directory you have two sub-directories: `scripts` and `src`.
The `scripts` directory consists of a series of scripts we will use here to install,
instantiate, invoke and query a chaincode on the Blockchain.
The `src` directory contains the smart-contract used in this example.
Note that, this section does not aim at teaching the reader how to develop a smart-contrat.
Instead, by the end of this section we expect to show how to use (install, invoke, etc)
a simple chaincode.

[[using_chaincode]]
The chaincode used in this first example can be found here in Appendix section.
For more details about the chaincode, please check the <<appendix:chaincode, appendix E>>.
Now go to the directory `~/hyperledger_ws/chaincode_examples/example1/scripts`
to run this example.

Basically what we are doing with this chaincode is to create two entities,
entity A and entity B and associating some assets to each.
If you look at the code in  <<appendix:chaincode, appendix E>> you can easily
identify these entities and assets at lines 99 to 102 as shown below.

[source, go]
----
99   var A, B string    // Entities
100  var Aval, Bval int // Asset holdings
101  var X int          // Transaction value
102  var err error
----

We are going instantiate the assets with some specific values using the
method `init` of the chaincode. In this example we set the initial values of
`A` and `B` to be `Aval=100` and `Bval=200` by passing these values as arguments
during the instantiation of the chaincode.  After instantiating it and therefore,
writing their values in the blockchain we are going to invoke the deployed
chaincode to perform a transaction that will transfer some assets from `A` to `B`.
Just before and after this transaction we make a query to verify the correctness
of the execution.


.1. Install chaincode peer1-org1

First, lets install the chaincode in two of your peer nodes, `peer1` and `peer2`.
In order to install a chaincode in Hyperledger Fabric you have to use the command
`peer chainode install`.

The script below prepares the environment variables required to install the chaincode
and runs the install command. Run the script as shown below.

[source, bash]
----
$ ./17_validate_1_install_cc_peer1.sh org1 peer1

====> 1 Installing chaincode (may fail if CC/version already there) on peer1
ORG_NAME: org1, PEER_NAME: peer1, PEER_IP_ADDRESS: 192.168.1.15 , PEER_BASE_PORT: 7050, IDENTITY: admin
##########################################################################
CRYPTO_CONFIG_ROOT_FOLDER: /home/ubuntu/hyperledger_ws/ca-client
CORE_PEER_MSPCONFIGPATH: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric/org1/peer1
MSP_ID: Org1
CORE_PEER_LOCALMSPID: Org1MSP
NODECHAINCODE: /home/ubuntu/hyperledger_ws/fabric/org1/peer1/chaincode_example/nodechaincode
CORE_PEER_FILESYSTEM_PATH: /var/ledgers/org1/peer1/ledger
CORE_PEER_LISTENADDRESS: 192.168.1.15:7051
CORE_PEER_ADDRESS: 192.168.1.15:7051
CORE_PEER_CHAINCODELISTENADDRESS: 192.168.1.15:7052
CORE_PEER_EVENTS_ADDRESS: 192.168.1.15:7053
CORE_PEER_GOSSIP_BOOTSTRAP: 192.168.1.15:7051
PEER_LOGS: /home/ubuntu/hyperledger_ws/fabric/org1/peer1
##########################################################################
peer chaincode install  -n gocc -p example1/ -v 1.0
2019-10-10 09:19:26.965 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-10-10 09:19:26.965 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-10-10 09:19:27.333 UTC [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:OK >
----

.2. Install chaincode peer2-org1

Now lets proceed in the same way in order to install the chaincode in the peer2.
Use the script below that will prepare the environment variables and run the
`peer chaincode install` command.

[source, bash]
----
$ ./17_validate_2_install_cc_peer2.sh org1 peer2

====> 1 Installing chaincode (may fail if CC/version already there) on peer2
ORG_NAME: org1, PEER_NAME: peer2, PEER_IP_ADDRESS: 192.168.1.17 , PEER_BASE_PORT: 7050, IDENTITY: admin
##########################################################################
CRYPTO_CONFIG_ROOT_FOLDER: /home/ubuntu/hyperledger_ws/ca-client
CORE_PEER_MSPCONFIGPATH: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric/org1/peer2
MSP_ID: Org1
CORE_PEER_LOCALMSPID: Org1MSP
NODECHAINCODE: /home/ubuntu/hyperledger_ws/fabric/org1/peer2/chaincode_example/nodechaincode
CORE_PEER_FILESYSTEM_PATH: /var/ledgers/org1/peer2/ledger
CORE_PEER_LISTENADDRESS: 192.168.1.17:7051
CORE_PEER_ADDRESS: 192.168.1.17:7051
CORE_PEER_CHAINCODELISTENADDRESS: 192.168.1.17:7052
CORE_PEER_EVENTS_ADDRESS: 192.168.1.17:7053
CORE_PEER_GOSSIP_BOOTSTRAP: 192.168.1.17:7051
PEER_LOGS: /home/ubuntu/hyperledger_ws/fabric/org1/peer2
##########################################################################
peer chaincode install  -n gocc -p example1/ -v 1.0
2019-10-10 09:24:17.709 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-10-10 09:24:17.709 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-10-10 09:24:18.045 UTC [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" >

----

.3. Instantiate chaincode

Now lets instantiate the chaincode.
The instantiate command deploys the specified chaincode to the network.
In practice this command creates a docker container a peer1 which will execute
any invocation of the chaincode in peer1.

[source, bash]
----
$ ./17_validate_3_instantiate_cc_peer1.sh org1 peer1

====> 2   Instantiating chaincode (may fail if CC/version already instantiated) on peer1
ORG_NAME: org1, PEER_NAME: peer1, PEER_IP_ADDRESS: 192.168.1.15 , PEER_BASE_PORT: 7050, IDENTITY: admin
##########################################################################
CRYPTO_CONFIG_ROOT_FOLDER: /home/ubuntu/hyperledger_ws/ca-client
CORE_PEER_MSPCONFIGPATH: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric/org1/peer1
MSP_ID: Org1
CORE_PEER_LOCALMSPID: Org1MSP
NODECHAINCODE: /home/ubuntu/hyperledger_ws/fabric/org1/peer1/chaincode_example/nodechaincode
CORE_PEER_FILESYSTEM_PATH: /var/ledgers/org1/peer1/ledger
CORE_PEER_LISTENADDRESS: 192.168.1.15:7051
CORE_PEER_ADDRESS: 192.168.1.15:7051
CORE_PEER_CHAINCODELISTENADDRESS: 192.168.1.15:7052
CORE_PEER_EVENTS_ADDRESS: 192.168.1.15:7053
CORE_PEER_GOSSIP_BOOTSTRAP: 192.168.1.15:7051
PEER_LOGS: /home/ubuntu/hyperledger_ws/fabric/org1/peer1
##########################################################################
peer chaincode instantiate -C mychannelid -n gocc  -v 1.0 -c {"Args":["init","a","100","b","200"]}
2019-10-10 09:25:44.415 UTC [chaincodeCmd] InitCmdFactory -> INFO 001 Retrieved channel (mychannelid) orderer endpoint: 192.168.1.14:7050
2019-10-10 09:25:44.417 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default escc
2019-10-10 09:25:44.417 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default vscc

----


.4. Query the Blockchain to check the value of assets

Now, lets check the value of the assets associated to the entity `A` in the blockchain.
You can do that by using the query method provided by our chaincode.
For instance, for querying the value of `A` at peer2 use the following script.

[source, bash]
----
ubuntu@msp-admin-org1:~/hyperledger_ws/chaincode_examples/example1/deployment$ ./17_validate_4_exec_query_A_peer2.sh.sh org1 peer2
====> 4. Querying for value of A on peer2
ORG_NAME: org1, PEER_NAME: peer2, PEER_IP_ADDRESS: 192.168.1.17 , PEER_BASE_PORT: 7050, IDENTITY: admin
##########################################################################
CRYPTO_CONFIG_ROOT_FOLDER: /home/ubuntu/hyperledger_ws/ca-client
CORE_PEER_MSPCONFIGPATH: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric/org1/peer2
MSP_ID: Org1
CORE_PEER_LOCALMSPID: Org1MSP
NODECHAINCODE: /home/ubuntu/hyperledger_ws/fabric/org1/peer2/chaincode_example/nodechaincode
CORE_PEER_FILESYSTEM_PATH: /var/ledgers/org1/peer2/ledger
CORE_PEER_LISTENADDRESS: 192.168.1.17:7051
CORE_PEER_ADDRESS: 192.168.1.17:7051
CORE_PEER_CHAINCODELISTENADDRESS: 192.168.1.17:7052
CORE_PEER_EVENTS_ADDRESS: 192.168.1.17:7053
CORE_PEER_GOSSIP_BOOTSTRAP: 192.168.1.17:7051
PEER_LOGS: /home/ubuntu/hyperledger_ws/fabric/org1/peer2

##########################################################################
peer chaincode query -C mychannelid -n gocc  -c '{'Args':['query','a']}'
100
----

We can see the result of the query at the last line (i.e., Aval=100).


.5. Make a transaction to invoke a smart-contrat and transfer some assets

Now, lets transfer some value `X` from `A` to `B`.
In order to do that, we will use the `invoke` method of our chaincode which
will simply propose a new state for the assets by removing the value `X` from `A`
and adding this value to `B` , as show in lines 142-143 of the chaincode.
In the current example we are sending 10 units from `A` to `B`.

[source, go]
----
142  Aval = Aval - X
143  Bval = Bval + X
----


In order to make this transfer, use the script below.

[source, bash]
----

ubuntu@msp-admin-org1:~/hyperledger_ws/chaincode_examples/example1/deployment$ ./17_validate_5_invoke_cc_peer1.sh org1 peer1
====> 5. Execute invoke on peer1 - Transfer 10 from A=>B
ORG_NAME: org1, PEER_NAME: peer1, PEER_IP_ADDRESS: 192.168.1.15 , PEER_BASE_PORT: 7050, IDENTITY: admin
##########################################################################
CRYPTO_CONFIG_ROOT_FOLDER: /home/ubuntu/hyperledger_ws/ca-client
CORE_PEER_MSPCONFIGPATH: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric/org1/peer1
MSP_ID: Org1
CORE_PEER_LOCALMSPID: Org1MSP
NODECHAINCODE: /home/ubuntu/hyperledger_ws/fabric/org1/peer1/chaincode_example/nodechaincode
CORE_PEER_FILESYSTEM_PATH: /var/ledgers/org1/peer1/ledger
CORE_PEER_LISTENADDRESS: 192.168.1.15:7051
CORE_PEER_ADDRESS: 192.168.1.15:7051
CORE_PEER_CHAINCODELISTENADDRESS: 192.168.1.15:7052
CORE_PEER_EVENTS_ADDRESS: 192.168.1.15:7053
CORE_PEER_GOSSIP_BOOTSTRAP: 192.168.1.15:7051
PEER_LOGS: /home/ubuntu/hyperledger_ws/fabric/org1/peer1
##########################################################################
peer chaincode invoke -C mychannelid -n gocc  -c '{'Args':['invoke','a','b','10']}'
2019-10-10 09:30:53.858 UTC [chaincodeCmd] InitCmdFactory -> INFO 001 Retrieved channel (mychannelid) orderer endpoint: 192.168.1.14:7050
2019-10-10 09:30:53.873 UTC [chaincodeCmd] chaincodeInvokeOrQuery -> INFO 002 Chaincode invoke successful. result: status:200
----

.6. Query the Blockchain again to check the new value of assets

Finally, lets check the values of assets belonging the entities.
Note, that both values belonging to both entities can be verified.
In the script below we are checking the assets of entity `A` in peer2.


[source, bash]
----

$ ./17_validate_6_exec_query_A_peer2.sh org1 peer2

====> 6.  Querying for value of A in peer2
ORG_NAME: org1, PEER_NAME: peer2, PEER_IP_ADDRESS: 192.168.1.17 , PEER_BASE_PORT: 7050, IDENTITY: admin
##########################################################################
CRYPTO_CONFIG_ROOT_FOLDER: /home/ubuntu/hyperledger_ws/ca-client
CORE_PEER_MSPCONFIGPATH: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric/org1/peer2
MSP_ID: Org1
CORE_PEER_LOCALMSPID: Org1MSP
NODECHAINCODE: /home/ubuntu/hyperledger_ws/fabric/org1/peer2/chaincode_example/nodechaincode
CORE_PEER_FILESYSTEM_PATH: /var/ledgers/org1/peer2/ledger
CORE_PEER_LISTENADDRESS: 192.168.1.17:7051
CORE_PEER_ADDRESS: 192.168.1.17:7051
CORE_PEER_CHAINCODELISTENADDRESS: 192.168.1.17:7052
CORE_PEER_EVENTS_ADDRESS: 192.168.1.17:7053
CORE_PEER_GOSSIP_BOOTSTRAP: 192.168.1.17:7051
PEER_LOGS: /home/ubuntu/hyperledger_ws/fabric/org1/peer2
##########################################################################
peer chaincode query -C mychannelid -n gocc  -c '{'Args':['query','a']}'
90

----


After sending 10 units, we see in the log above that the new value of `Aval` is 90, as we expected. Concluding our example.
