
#############################################################################
#   Orange Admin Client YAML file 
#   Changes to the CSR
#############################################################################
# File originally at: 
# ../setup/config/multi-org-ca/yaml.0/budget/fabric-ca-client-config.yaml
#
#############################################################################
# Client Configuration
#############################################################################

# URL of the Fabric-ca-server (default: http://localhost:7054)
# url: http://localhost:7054
url: http://192.168.1.10:7054

# Membership Service Provider (MSP) directory
mspdir: msp

#############################################################################
#    TLS Disabled by default
#############################################################################
tls:
  # TLS section for secure socket connection
  certfiles:
  client:
    certfile:
    keyfile:

#############################################################################
#
#############################################################################
csr:
  cn: org2-admin
  serialnumber:
  names:
    - C: FR
      ST: "Bretagne"
      L:  "Rennes"
      O: org2
      OU: 
  hosts:
    - msp-admin-org2
    - localhost

#############################################################################
#  Registration section used to register a new identity with fabric-ca server
#############################################################################
id:
  # Must override the name
  name: XYZ
  # By default the type is set to be user
  type: user
  # Default org is org1 - make sure the org is set up in CA server :-)
  affiliation: org2
  # Set to max of 2
  maxenrollments: 5
  # Adds a custom attribute
  attributes:
  #  - name: myAttribute:ecert
  #    value: val

#############################################################################
#  Enrollment section used to enroll an identity with fabric-ca server
#  profile - Name of the signing profile to use in issuing the certificate
#  label - Label to use in HSM operations
#############################################################################
enrollment:
  profile:
  label:

#############################################################################
# Name of the CA to connect to within the fabric-ca server
#############################################################################
caname:

#############################################################################
# BCCSP (BlockChain Crypto Service Provider) section allows to select which
# crypto implementation library to use
#############################################################################
bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            # The directory used for the software file-based keystore
            keystore: msp/keystore