
#############################################################################
#   Peer 2 identity Client YAML file 
#   Changes to the CSR
#############################################################################
# File originally at: 
# ../setup/config/multi-org-ca/yaml.0/identities/orderer/fabric-ca-client-config.yaml
#
#############################################################################
# Client Configuration
#############################################################################

# URL of the Fabric-ca-server (default: http://localhost:7054)
url: http://192.168.1.10:7054

# Membership Service Provider (MSP) directory
mspdir: msp

#############################################################################
#    TLS Disabled by default
#############################################################################
tls:
  # TLS section for secure socket connection
  certfiles:
  client:
    certfile:
    keyfile:

#############################################################################
#
#############################################################################
csr:
  cn: peer2
  serialnumber:
  names:
    - C: FR
      ST: "Bretagne"
      L:  "Rennes"
      O:  org1
      OU: 
  hosts:
    - peer2-org1
    - localhost

#############################################################################
#  Registration section used to register a new identity with fabric-ca server
#############################################################################
id:
  name: peer2
  type: peer
  affiliation: org1
  maxenrollments: 0
  attributes:

#############################################################################
#  Enrollment section used to enroll an identity with fabric-ca server
#
#  profile - Name of the signing profile to use in issuing the certificate
#  label - Label to use in HSM operations
#############################################################################
enrollment:
  profile:
  label:

#############################################################################
# Name of the CA to connect to within the fabric-ca server
#############################################################################
caname:

#############################################################################
# BCCSP (BlockChain Crypto Service Provider) section allows to select which
# crypto implementation library to use
#############################################################################
bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            # The directory used for the software file-based keystore
            keystore: msp/keystore
