# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "bento/ubuntu-16.04"
    config.ssh.username = "ubuntu"
    config.ssh.insert_key = 'true'

    # accessing "localhost:8080" will access port 80 on the guest machine.
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.network "private_network", ip: "192.168.33.10"
    # config.vm.network "public_network"
    # config.vm.synced_folder "../data", "/vagrant_data"
    #
  
    config.vm.define "server" do |server| 
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.33.20"
    end
    
    #config.vm.define "client" do |client|
    #  client.vm.hostname = "client"
    #  client.vm.network "private_network", ip: "192.168.33.30"
    #end
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = 'ubuntu'
    #   vb.gui = true
    #   vb.memory = "1024"
    end
    #
    # config.vm.provision "shell", inline: <<-SHELL
    #   sudo apt-get update
    #   sudo apt-get install -y apache2
    # SHELL
  end