=== Configure the Hyperledger Blockchain

==== Generate the genesis block and channel transaction

Go to `msp-admin-orderer` node. From the `setup_scripts` directory run the following commands.

.1. Recover the public certificates to sign
[source, bash]
----
$ ./05_get_org-pub-certs.sh org1
=> Using ORG_NAME: org1
=> Using ORG_HOSTNAME: msp-admin-org1
Getting admin certs with SCP
scp -r msp-admin-org1:/home/ubuntu/hyperledger_ws/ca-client/org1/msp/  /home/ubuntu/hyperledger_ws/ca-client/org1/msp
cert.pem   100%  997     1.0KB/s   00:00
ca-cert.pem
----

.2. Generate the genesis block.

[source, bash]
----
$ ./06_generate_genesis-block.sh

orderer folder does not exist, creating it
################################################
using FABRIC_CFG_PATH : /home/ubuntu/hyperledger_ws/fabric
################################################
================ Writing the Genesis Block ================
2019-10-17 15:43:18.686 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2019-10-17 15:43:18.721 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2019-10-17 15:43:18.721 UTC [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-17 15:43:18.753 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 004 orderer type: solo
2019-10-17 15:43:18.753 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 005 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-17 15:43:18.756 UTC [common.tools.configtxgen] doOutputBlock -> INFO 006 Generating genesis block
2019-10-17 15:43:18.756 UTC [common.tools.configtxgen] doOutputBlock -> INFO 007 Writing genesis block
#########################################################################################
you can use ' configtxgen -inspectBlock /home/ubuntu/hyperledger_ws/fabric/my_genesis.block ' to verifiy the generated block
NOTE: check the variable FABRIC_CFG_PATH before. it must be : /home/ubuntu/hyperledger_ws/fabric
#########################################################################################

----

You can use the command `configtxgen -inspectBlock /home/ubuntu/hyperledger_ws/fabric/my_genesis.block`
to verify if the genesis block was well generated.

[[channel-tx_create]]
.3. Generate the transaction to create the channel.

[source, bash]
----
$ ./07_generate_channel-tx.sh

================ Writing $CHANNELID ================
2019-10-17 15:46:20.366 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2019-10-17 15:46:20.400 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-17 15:46:20.438 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 003 orderer type: solo
2019-10-17 15:46:20.439 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 004 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-17 15:46:20.439 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 005 Generating new channel configtx
2019-10-17 15:46:20.441 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 006 Writing new channel tx
you can use ' configtxgen -inspectChannelCreateTx  /home/ubuntu/hyperledger_ws/fabric/my-channel.tx ' to verifiy the generated channel
======= Done. Launch by executing orderer ======

----

==== Register enroll and start orderer service

Still in the `msp-admin-orderer` node run the following command to register the
orderer node. Pay attention to the arguments.

.1. Register orderer node
[source, bash]
----
$ ./08_register_orderer-node.sh orderer-node

Switching PEER_NAME for Org =
PEER_PW=pw
ORG_NAME=orderer
my FABRIC_CA_CLIENT_HOME:
now FABRIC_CA_CLIENT_HOME: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin
##################################################
# Registering orderer identity with orderer-admin
##################################################
FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/orderer/admin
Registering :=> fabric-ca-client register --id.type orderer --id.name orderer --id.secret pw --id.affiliation orderer
2019/10/17 15:50:11 [INFO] Configuration file location: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml
Password: pw
======Completed: Step 1 : Registered orderer (can be done only once)====
----


.2. Enroll orderer

Go to the host `orderer-node` and enroll the node, similarly as we did for the
adminstrator before. Use the following script from the `setup_scripts` directory.


[source, bash]
----
$ ./09_enroll_orderer-node.sh orderer-node
Switching ORDERER_NAME to orderer-node
ORDERER_PW=pw
ORG_NAME=orderer
CA_ORG_ADMIN_HOSTNAME=msp-admin-orderer
##############################################################
ADMIN_CLIENT_HOME: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin
##############################################################
changing identity to [orderer-node]
my FABRIC_CA_CLIENT_HOME:
now FABRIC_CA_CLIENT_HOME: /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node
/home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml not found in /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/
creating : mkdir -p /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node
Copy Yaml from: /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config-orderer-node.yaml
cp /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config-orderer-node.yaml  /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml
checking with: ls /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml
/home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml
File /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml found.
======Completed: Step 1 : Copy Check Orderer Client YAML==========
###################################
# Enrolling: orderer
###################################
enrolling :=> fabric-ca-client enroll -u http://orderer-node:pw@192.168.1.10:7054
2019/10/17 15:52:38 [INFO] generating key: &{A:ecdsa S:256}
2019/10/17 15:52:38 [INFO] encoded CSR
2019/10/17 15:52:38 [INFO] Stored client certificate at /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/signcerts/cert.pem
2019/10/17 15:52:38 [INFO] Stored root CA certificate at /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/cacerts/192-168-1-10-7054.pem
2019/10/17 15:52:38 [INFO] Stored Issuer public key at /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/IssuerPublicKey
2019/10/17 15:52:38 [INFO] Stored Issuer revocation public key at /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/IssuerRevocationPublicKey
======Completed: Step 2 : Enrolled orderer ========
###################################
# Setting up admincerts
###################################
DEBUG-ONLY: /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node == /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node ???
Creating /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts
====> /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts
Copying [/home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/signcerts] from host [msp-admin-orderer] here at [/home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts]
Getting orderer-admin certs with SCP
scp msp-admin-orderer:/home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/signcerts/* /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts
cert.pem    100% 1017     1.0KB/s   00:00
Checking with: ls /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts/
cert.pem
File(s) found at /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts/.
======Completed: Step 3 : MSP setup for the orderer ========
----

If the enrollment went well, now you are able to start the orderer node.
Please run the following.

.3. Start orderer service
[source, bash]
----
$ ./10_start_orderer.sh

FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric
/var/ledgers does not exist, creating it
/home/ubuntu/hyperledger_ws/fabric does not exist, creating it
/home/ubuntu/hyperledger_ws/fabric/configtx.yaml not found. copying from /home/ubuntu/hyperledger_ws/config_files
/home/ubuntu/hyperledger_ws/fabric/orderer.yaml not found. copying from /home/ubuntu/hyperledger_ws/config_files
/home/ubuntu/hyperledger_ws/fabric/core.yaml not found. copying from /home/ubuntu/hyperledger_ws/config_files
#######################################################################
getting GENESIS_BLK_NAME from orderer admin using scp
scp ubuntu@msp-admin-orderer:/home/ubuntu/hyperledger_ws/fabric/my_genesis.block /home/ubuntu/hyperledger_ws/fabric
my_genesis.block  100% 8102     7.9KB/s   00:00
my_genesis.block
file my_genesis.block found at /home/ubuntu/hyperledger_ws/fabric
===> Done. Please check logs under /home/ubuntu/hyperledger_ws/fabric/orderer.log
----

If no errors are reported, check the following log to see details about the orderer
launching.

[[start_orderer]]
[source, bash]
----
$ less /home/ubuntu/hyperledger_ws/fabric/orderer.log
----


You can check  the full log of the orderer node starting at section
<<appendix:orderer-node-start, Appendix C: Output logs from Blockchain setup>>.



==== Create the channel

In order to create submit the channel for its instantiation we have previously
<<channel-tx_create, generated the transaction>>  to create our channel.
The next step, in order to really create the channel in Hyperledger is to sign
and submit this transaction to be executed.

11_sign_channel-tx.sh
[source, bash]
----

----

12_submit_create_channel.sh
[source, bash]
----

----


==== Create, start and join peers to the Blockchains

13_peer_register.sh
[source, bash]
----

----

14_peer_enroll.sh
[source, bash]
----

----

15_start_peer.sh
[source, bash]
----

----

16_join_channel.sh
[source, bash]
----

----
