


./01_start_ca_server.sh
-----------------------------------------------------------------------------------------
Starting CA-Server
-----------------------------------------------------------------------------------------
checking /home/ubuntu/hyperledger_ws/ca-server/fabric-ca-server-config.yaml
Server YAML not found in /home/ubuntu/hyperledger_ws/ca-server/
Copying /home/ubuntu/hyperledger_ws/config_files/fabric-ca-server-config.yaml to /home/ubuntu/hyperledger_ws/ca-server
Starting server with: /home/ubuntu/hyperledger_ws/ca-server/fabric-ca-server-config.yaml
Server Started ... Logs available at /home/ubuntu/hyperledger_ws/ca-server/ca-server.log
---------------------------- /home/ubuntu/hyperledger_ws/ca-server/ca-server.log -----------------------------------
2019/10/16 17:17:13 [INFO] Configuration file location: /home/ubuntu/hyperledger_ws/ca-server/fabric-ca-server-config.yaml
2019/10/16 17:17:13 [INFO] Starting server in home directory: /home/ubuntu/hyperledger_ws/ca-server
2019/10/16 17:17:13 [WARNING] Unknown provider type: ; metrics disabled
2019/10/16 17:17:13 [INFO] Server Version: 1.4.4
2019/10/16 17:17:13 [INFO] Server Levels: &{Identity:2 Affiliation:1 Certificate:1 Credential:1 RAInfo:1 Nonce:1}
2019/10/16 17:17:13 [WARNING] &{69 The specified CA certificate file /home/ubuntu/hyperledger_ws/ca-server/ca-cert.pem does not exist}
2019/10/16 17:17:13 [INFO] generating key: &{A:ecdsa S:256}
2019/10/16 17:17:13 [INFO] encoded CSR
2019/10/16 17:17:13 [INFO] signed certificate with serial number 509693231792453412521639879563657408592713615338
2019/10/16 17:17:13 [INFO] The CA key and certificate were generated for CA ca-root
2019/10/16 17:17:13 [INFO] The key was stored by BCCSP provider 'SW'
2019/10/16 17:17:13 [INFO] The certificate is at: /home/ubuntu/hyperledger_ws/ca-server/ca-cert.pem
2019/10/16 17:17:14 [INFO] Initialized sqlite3 database at /home/ubuntu/hyperledger_ws/ca-server/fabric-ca-server.db
2019/10/16 17:17:14 [INFO] The issuer key was successfully stored. The public key is at: /home/ubuntu/hyperledger_ws/ca-server/IssuerPublicKey, secret key is at: /home/ubuntu/hyperledger_ws/ca-server/msp/keystore/IssuerSecretKey
2019/10/16 17:17:14 [INFO] Idemix issuer revocation public and secret keys were generated for CA 'ca-root'
2019/10/16 17:17:14 [INFO] The revocation key was successfully stored. The public key is at: /home/ubuntu/hyperledger_ws/ca-server/IssuerRevocationPublicKey, private key is at: /home/ubuntu/hyperledger_ws/ca-server/msp/keystore/IssuerRevocationPrivateKey
2019/10/16 17:17:14 [INFO] Home directory for default CA: /home/ubuntu/hyperledger_ws/ca-server
2019/10/16 17:17:14 [INFO] Operation Server Listening on [::]:45340
2019/10/16 17:17:14 [INFO] Listening on http://192.168.1.10:7054
---------------------------- /home/ubuntu/hyperledger_ws/ca-server/ca-server.log -----------------------------------
ubuntu@msp-root-org1:~/hyperledger_ws/setup_scripts$







./02_enroll_bootstrap_identity.sh
-----------------------------------------------------------------------------------------
Enrolling bootstrap Identity
-----------------------------------------------------------------------------------------
current FABRIC_CA_CLIENT_HOME=
now FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/caserver/admin
File [fabric-ca-client-config.yaml] not found in [/home/ubuntu/hyperledger_ws/ca-client/caserver/admin/]
mkdir -p /home/ubuntu/hyperledger_ws/ca-client/caserver/admin
Copying /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config.yaml to /home/ubuntu/hyperledger_ws/ca-client/caserver/admin
Enrolling bootstrap Identity (ca-client) with: /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/fabric-ca-client-config.yaml
fabric-ca-client enroll -u http://admin:pw@192.168.1.10:7054
2019/10/16 17:17:41 [INFO] generating key: &{A:ecdsa S:256}
2019/10/16 17:17:41 [INFO] encoded CSR
2019/10/16 17:17:41 [INFO] Stored client certificate at /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts/cert.pem
2019/10/16 17:17:41 [INFO] Stored root CA certificate at /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/cacerts/192-168-1-10-7054.pem
2019/10/16 17:17:41 [INFO] Stored Issuer public key at /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/IssuerPublicKey
2019/10/16 17:17:41 [INFO] Stored Issuer revocation public key at /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/IssuerRevocationPublicKey
-------------- showing identities ----------------------
Name: admin, Type: client, Affiliation: , Max Enrollments: -1, Attributes: [{Name:hf.Revoker Value:1 ECert:false} {Name:hf.IntermediateCA Value:1 ECert:false} {Name:hf.GenCRL Value:1 ECert:false} {Name:hf.Registrar.Attributes Value:* ECert:false} {Name:hf.AffiliationMgr Value:1 ECert:false} {Name:hf.Registrar.Roles Value:* ECert:false} {Name:hf.Registrar.DelegateRoles Value:* ECert:false}]
--------------------------------------------------------





./03_register_admin.sh
-----------------------------------------------------------------------------
USAGE: ./register_admin.sh <type> <name> <pass> <organization> <affiliation>
  ex: ./03_register_admin.sh client  org1-admin     pw  org1    org1
  ex: ./03_register_admin.sh client  org2-admin     pw  org2    org2
  ex: ./03_register_admin.sh client  orderer-admin  pw  orderer orderer
------------------------------------------------------------------------------
ubuntu@msp-root-org1:~/hyperledger_ws/setup_scripts$  ./03_register_admin.sh client  org1-admin     pw  org1    org1
current FABRIC_CA_CLIENT_HOME=
now FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/caserver/admin
Registering: org1-admin
2019/10/16 17:18:27 [INFO] Configuration file location: /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/fabric-ca-client-config.yaml
Password: pw
NOTE:  inform the user <org1-admin> and password <pw> to the admin of the organization <org1> (this information is also required to enroll organization's clients)
ubuntu@msp-root-org1:~/hyperledger_ws/setup_scripts$ ./03_register_admin.sh client  orderer-admin  pw  orderer orderer
current FABRIC_CA_CLIENT_HOME=
now FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/caserver/admin
registering an orderer , setting attributes
Registering: orderer-admin
2019/10/16 17:18:39 [INFO] Configuration file location: /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/fabric-ca-client-config.yaml
Password: pw
NOTE:  inform the user <orderer-admin> and password <pw> to the admin of the organization <orderer> (this information is also required to enroll organization's clients)
ubuntu@msp-root-org1:~/hyperledger_ws/setup_scripts$






ubuntu@msp-root-org1:~/hyperledger_ws/setup_scripts$ ./list_ca-server_identity-list.sh
------------Fabric ENV -----------------
########## LIST ENV VARS ################
FABRIC_CA_SERVER_CONFIG_FILE=fabric-ca-server-config.yaml
FABRIC_VERSION=1.4.0
FABRIC_LOGGING_SPEC=INFO
FABRIC_CA_CLIENT_CONFIG_FILE=fabric-ca-client-config.yaml
FABRIC_USER=ubuntu
FABRIC_CA_SERVER_HOME=/home/ubuntu/hyperledger_ws/ca-server
BASE_FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client
FABRIC_CFG_PATH=/home/ubuntu/hyperledger_ws/fabric
FABRIC_CA_SERVER_LOG=/home/ubuntu/hyperledger_ws/ca-server/ca-server.log
#########################################
#########################################
#########################################
------------Setting HOME ---------------
current FABRIC_CA_CLIENT_HOME=
now FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/caserver/admin
------------Listing Identities----------
Name: admin, Type: client, Affiliation: , Max Enrollments: -1, Attributes: [{Name:hf.Revoker Value:1 ECert:false} {Name:hf.IntermediateCA Value:1 ECert:false} {Name:hf.GenCRL Value:1 ECert:false} {Name:hf.Registrar.Attributes Value:* ECert:false} {Name:hf.AffiliationMgr Value:1 ECert:false} {Name:hf.Registrar.Roles Value:* ECert:false} {Name:hf.Registrar.DelegateRoles Value:* ECert:false}]
Name: org1-admin, Type: client, Affiliation: org1, Max Enrollments: -1, Attributes: [{Name:hf.Registrar.Roles Value:peer,user,client ECert:false} {Name:hf.AffiliationMgr Value:true ECert:false} {Name:hf.Revoker Value:true ECert:false} {Name:hf.EnrollmentID Value:org1-admin ECert:true} {Name:hf.Type Value:client ECert:true} {Name:hf.Affiliation Value:org1 ECert:true}]
Name: orderer-admin, Type: client, Affiliation: orderer, Max Enrollments: -1, Attributes: [{Name:hf.Registrar.Roles Value:orderer ECert:false} {Name:hf.EnrollmentID Value:orderer-admin ECert:true} {Name:hf.Type Value:client ECert:true} {Name:hf.Affiliation Value:orderer ECert:true}]
----------------------------------------
ubuntu@msp-root-org1:~/hyperledger_ws/setup_scripts$






./04_enroll_admin_and_setup_msp.sh
-------------------------------------------------------------
USAGE: ./04_enroll_admin_and_setup_msp.sh <org_name> <ca-admin_HOSTNAME> <ca-admin_host_IP>
   EX: ./04_enroll_admin_and_setup_msp.sh org1    msp-root-org1 192.168.1.10
   EX: ./04_enroll_admin_and_setup_msp.sh org2    msp-root-org1 192.168.1.10
   EX: ./04_enroll_admin_and_setup_msp.sh orderer msp-root-org1 192.168.1.10
-------------------------------------------------------------
ubuntu@msp-admin-org1:~/hyperledger_ws/setup_scripts$ ./04_enroll_admin_and_setup_msp.sh org1    msp-root-org1 192.168.1.10
current FABRIC_CA_CLIENT_HOME=
now FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/org1/admin
/home/ubuntu/hyperledger_ws/ca-client/org1/admin/fabric-ca-client-config.yaml not found in /home/ubuntu/hyperledger_ws/ca-client/org1/admin/
creating : mkdir -p /home/ubuntu/hyperledger_ws/ca-client/org1/admin
Copy /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config-org1-admin.yaml  to /home/ubuntu/hyperledger_ws/ca-client/org1/admin/fabric-ca-client-config.yaml
checking with: ls /home/ubuntu/hyperledger_ws/ca-client/org1/admin/fabric-ca-client-config.yaml
/home/ubuntu/hyperledger_ws/ca-client/org1/admin/fabric-ca-client-config.yaml
File /home/ubuntu/hyperledger_ws/ca-client/org1/admin/fabric-ca-client-config.yaml found.
###################################
# Enrolling: org1-admin:
###################################
fabric-ca-client enroll -u http://org1-admin:pw@192.168.1.10:7054
2019/10/16 17:20:23 [INFO] generating key: &{A:ecdsa S:256}
2019/10/16 17:20:23 [INFO] encoded CSR
2019/10/16 17:20:24 [INFO] Stored client certificate at /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/signcerts/cert.pem
2019/10/16 17:20:24 [INFO] Stored root CA certificate at /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/cacerts/192-168-1-10-7054.pem
2019/10/16 17:20:24 [INFO] Stored Issuer public key at /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/IssuerPublicKey
2019/10/16 17:20:24 [INFO] Stored Issuer revocation public key at /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/IssuerRevocationPublicKey
###################################
# Setting up admincerts folder
###################################
Creating /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/admincerts
====> /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/admincerts
copying /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts/*  to /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/admincerts
directory /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts does not exist locally
getting admin certs using scp
scp msp-root-org1:/home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts/* /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/admincerts
The authenticity of host '192.168.1.10 (192.168.1.10)' can't be established.
ECDSA key fingerprint is SHA256:QGb/eYDuqmfeK1sQ0M+Kyo3EBScU2BoO4xIHSJdAPGM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.10' (ECDSA) to the list of known hosts.
cert.pem                                                                                                                                                                                                     100%  834     0.8KB/s   00:00
checking with: ls /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/admincerts/
cert.pem
create /home/ubuntu/hyperledger_ws/ca-client/org1/admin/../msp subfolders
scp msp-root-org1:/home/ubuntu/hyperledger_ws/ca-server/ca-cert.pem /home/ubuntu/hyperledger_ws/ca-client/org1/admin/../msp/cacerts
ca-cert.pem                                                                                                                                                                                                  100%  725     0.7KB/s   00:00
cp /home/ubuntu/hyperledger_ws/ca-client/org1/admin/msp/signcerts/* /home/ubuntu/hyperledger_ws/ca-client/org1/admin/../msp/admincerts
--------------------------------------------------------
Created MSP for org: org1 at: /home/ubuntu/hyperledger_ws/ca-client/org1/admin/..
-------------- Listing Identities ----------------------
Name: org1-admin, Type: client, Affiliation: org1, Max Enrollments: -1, Attributes: [{Name:hf.Registrar.Roles Value:peer,user,client ECert:false} {Name:hf.AffiliationMgr Value:true ECert:false} {Name:hf.Revoker Value:true ECert:false} {Name:hf.EnrollmentID Value:org1-admin ECert:true} {Name:hf.Type Value:client ECert:true} {Name:hf.Affiliation Value:org1 ECert:true}]
--------------------------------------------------------
ubuntu@msp-admin-org1:~/hyperledger_ws/setup_scripts$





ubuntu@msp-admin-org1:~/hyperledger_ws/setup_scripts$ tree ../ca-client/
../ca-client/
└── org1
    ├── admin
    │   ├── fabric-ca-client-config.yaml
    │   └── msp
    │       ├── admincerts
    │       │   └── cert.pem
    │       ├── cacerts
    │       │   └── 192-168-1-10-7054.pem
    │       ├── IssuerPublicKey
    │       ├── IssuerRevocationPublicKey
    │       ├── keystore
    │       │   └── 088d44c3c1931d5341b6fbced8e2f7712df901d7c1088ed192f7753a55063508_sk
    │       ├── signcerts
    │       │   └── cert.pem
    │       └── user
    └── msp
        ├── admincerts
        │   └── cert.pem
        ├── cacerts
        │   └── ca-cert.pem
        └── keystore

12 directories, 9 files
ubuntu@msp-admin-org1:~/hyperledger_ws/setup_scripts$








./04_enroll_admin_and_setup_msp.sh
-------------------------------------------------------------
USAGE: ./04_enroll_admin_and_setup_msp.sh <org_name> <ca-admin_HOSTNAME> <ca-admin_host_IP>
   EX: ./04_enroll_admin_and_setup_msp.sh org1    msp-root-org1 192.168.1.10
   EX: ./04_enroll_admin_and_setup_msp.sh org2    msp-root-org1 192.168.1.10
   EX: ./04_enroll_admin_and_setup_msp.sh orderer msp-root-org1 192.168.1.10
-------------------------------------------------------------
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ ./04_enroll_admin_and_setup_msp.sh orderer msp-root-org1 192.168.1.10
current FABRIC_CA_CLIENT_HOME=
now FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/orderer/admin
/home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml not found in /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/
creating : mkdir -p /home/ubuntu/hyperledger_ws/ca-client/orderer/admin
Copy /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config-orderer-admin.yaml  to /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml
checking with: ls /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml
/home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml
File /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml found.
###################################
# Enrolling: orderer-admin:
###################################
fabric-ca-client enroll -u http://orderer-admin:pw@192.168.1.10:7054
2019/10/16 17:20:58 [INFO] generating key: &{A:ecdsa S:256}
2019/10/16 17:20:58 [INFO] encoded CSR
2019/10/16 17:20:58 [INFO] Stored client certificate at /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/signcerts/cert.pem
2019/10/16 17:20:58 [INFO] Stored root CA certificate at /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/cacerts/192-168-1-10-7054.pem
2019/10/16 17:20:58 [INFO] Stored Issuer public key at /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/IssuerPublicKey
2019/10/16 17:20:58 [INFO] Stored Issuer revocation public key at /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/IssuerRevocationPublicKey
###################################
# Setting up admincerts folder
###################################
Creating /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/admincerts
====> /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/admincerts
copying /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts/*  to /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/admincerts
directory /home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts does not exist locally
getting admin certs using scp
scp msp-root-org1:/home/ubuntu/hyperledger_ws/ca-client/caserver/admin/msp/signcerts/* /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/admincerts
The authenticity of host '192.168.1.10 (192.168.1.10)' can't be established.
ECDSA key fingerprint is SHA256:QGb/eYDuqmfeK1sQ0M+Kyo3EBScU2BoO4xIHSJdAPGM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.10' (ECDSA) to the list of known hosts.
cert.pem                                                                                                                                                                                                     100%  834     0.8KB/s   00:00
checking with: ls /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/admincerts/
cert.pem
create /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/../msp subfolders
scp msp-root-org1:/home/ubuntu/hyperledger_ws/ca-server/ca-cert.pem /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/../msp/cacerts
ca-cert.pem                                                                                                                                                                                                  100%  725     0.7KB/s   00:00
cp /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/signcerts/* /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/../msp/admincerts
--------------------------------------------------------
Created MSP for org: orderer at: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/..
-------------- Listing Identities ----------------------
No results returned
--------------------------------------------------------
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$





ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ tree ../ca-client/
../ca-client/
└── orderer
    ├── admin
    │   ├── fabric-ca-client-config.yaml
    │   └── msp
    │       ├── admincerts
    │       │   └── cert.pem
    │       ├── cacerts
    │       │   └── 192-168-1-10-7054.pem
    │       ├── IssuerPublicKey
    │       ├── IssuerRevocationPublicKey
    │       ├── keystore
    │       │   └── 3131147c0041e311f9c1f041bd4f2195e373946b0e6e39aace5678092f3a398c_sk
    │       ├── signcerts
    │       │   └── cert.pem
    │       └── user
    └── msp
        ├── admincerts
        │   └── cert.pem
        ├── cacerts
        │   └── ca-cert.pem
        └── keystore

12 directories, 9 files
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$







ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ ./05_get_org-pub-certs.sh
-------------------------------------------------------------
USAGE: ./05_get_org-pub-certs <org_name> [admin_HOSTNAME , default=msp-admin-ORG_NAME]
   EX: ./05_get_org-pub-certs    org1    [msp-admin-org1]
-------------------------------------------------------------
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ ./05_get_org-pub-certs.sh org1
=> Using ORG_NAME: org1
=> Using ORG_HOSTNAME: msp-admin-org1
Getting admin certs with SCP
scp -r msp-admin-org1:/home/ubuntu/hyperledger_ws/ca-client/org1/msp/  /home/ubuntu/hyperledger_ws/ca-client/org1/msp
The authenticity of host '192.168.1.11 (192.168.1.11)' can't be established.
ECDSA key fingerprint is SHA256:TYKyd9F5BOYZoN2qEF2iVvJ9fpr9bU05HJV7CD8H3sQ.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.11' (ECDSA) to the list of known hosts.
cert.pem                                                                                                                                                                                                     100%  993     1.0KB/s   00:00
ca-cert.pem                                                                                                                                                                                                  100%  725     0.7KB/s   00:00
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ tree ../ca-client/
../ca-client/
├── orderer
│   ├── admin
│   │   ├── fabric-ca-client-config.yaml
│   │   └── msp
│   │       ├── admincerts
│   │       │   └── cert.pem
│   │       ├── cacerts
│   │       │   └── 192-168-1-10-7054.pem
│   │       ├── IssuerPublicKey
│   │       ├── IssuerRevocationPublicKey
│   │       ├── keystore
│   │       │   └── 3131147c0041e311f9c1f041bd4f2195e373946b0e6e39aace5678092f3a398c_sk
│   │       ├── signcerts
│   │       │   └── cert.pem
│   │       └── user
│   └── msp
│       ├── admincerts
│       │   └── cert.pem
│       ├── cacerts
│       │   └── ca-cert.pem
│       └── keystore
└── org1
    └── msp
        ├── admincerts
        │   └── cert.pem
        ├── cacerts
        │   └── ca-cert.pem
        └── keystore

17 directories, 11 files
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$








ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ ./06_generate_genesis-block.sh
orderer folder does not exist, creating it
################################################
using FABRIC_CFG_PATH : /home/ubuntu/hyperledger_ws/fabric
################################################
================ Writing the Genesis Block ================
2019-10-16 17:25:03.664 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2019-10-16 17:25:03.704 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2019-10-16 17:25:03.705 UTC [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-16 17:25:03.736 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 004 orderer type: solo
2019-10-16 17:25:03.737 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 005 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-16 17:25:03.738 UTC [common.tools.configtxgen] doOutputBlock -> INFO 006 Generating genesis block
2019-10-16 17:25:03.739 UTC [common.tools.configtxgen] doOutputBlock -> INFO 007 Writing genesis block
#########################################################################################
you can use ' configtxgen -inspectBlock /home/ubuntu/hyperledger_ws/fabric/my_genesis.block ' to verifiy the generated block
NOTE: check the variable FABRIC_CFG_PATH before. it must be : /home/ubuntu/hyperledger_ws/fabric
#########################################################################################
================ Done generating the Genesis Block ================






./07_generate_channel-tx.sh
================ Writing $CHANNELID ================
2019-10-16 17:25:25.984 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2019-10-16 17:25:26.018 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-16 17:25:26.048 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 003 orderer type: solo
2019-10-16 17:25:26.048 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 004 Loaded configuration: /home/ubuntu/hyperledger_ws/fabric/configtx.yaml
2019-10-16 17:25:26.048 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 005 Generating new channel configtx
2019-10-16 17:25:26.051 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 006 Writing new channel tx
you can use ' configtxgen -inspectChannelCreateTx  /home/ubuntu/hyperledger_ws/fabric/my-channel.tx ' to verifiy the generated channel
======= Done. Launch by executing orderer ======









ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ ./08_register_orderer-node.sh
Provide Orderer-node Name!!!
------------------------------------------------------------------------
USAGE: ./08_register_orderer-node.sh <ORDERER_NAME>  [PEER_PW , default=pw] [ORG_NAME , default=orderer]
   ex: ./08_register_orderer-node.sh orderer-node [pw] [orderer]
------------------------------------------------------------------------
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$ ./08_register_orderer-node.sh orderer-node [pw] [orderer]
Switching PEER_NAME for Org =
my FABRIC_CA_CLIENT_HOME:
now FABRIC_CA_CLIENT_HOME: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin
##################################################
# Registering orderer identity with orderer-admin
##################################################
FABRIC_CA_CLIENT_HOME=/home/ubuntu/hyperledger_ws/ca-client/orderer/admin
Registering :=> fabric-ca-client register --id.type orderer --id.name orderer --id.secret pw --id.affiliation orderer
2019/10/16 17:25:50 [INFO] Configuration file location: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin/fabric-ca-client-config.yaml
Password: [pw]
======Completed: Step 1 : Registered orderer (can be done only once)====
ubuntu@msp-admin-orderer:~/hyperledger_ws/setup_scripts$







ubuntu@orderer-node:~/hyperledger_ws/setup_scripts$ ./09_enroll_orderer-node.sh
Provide Orderer-node Name!!!
------------------------------------------------------------------------
USAGE: ./09_enroll_orderer-node.sh <ORDERER_NAME>  [ORDERER_PW , default=pw] [ORG_NAME , default=orderer] [<ORG-ADMIN-HOSTNAME , default=msp-admin-orderer]
   ex: ./09_enroll_orderer-node.sh orderer-node pw orderer msp-admin-orderer
   ex: ./09_enroll_orderer-node.sh orderer-node
------------------------------------------------------------------------
ubuntu@orderer-node:~/hyperledger_ws/setup_scripts$ ./09_enroll_orderer-node.sh orderer-node
Switching ORDERER_NAME to orderer-node
ORDERER_PW=pw
ORG_NAME=orderer
CA_ORG_ADMIN_HOSTNAME=msp-admin-orderer
##############################################################
ADMIN_CLIENT_HOME: /home/ubuntu/hyperledger_ws/ca-client/orderer/admin
##############################################################
changing identity to [orderer-node]
my FABRIC_CA_CLIENT_HOME:
now FABRIC_CA_CLIENT_HOME: /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node
/home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml not found in /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/
creating : mkdir -p /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node
Copy Yaml from: /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config-orderer-node.yaml
cp /home/ubuntu/hyperledger_ws/config_files/fabric-ca-client-config-orderer-node.yaml  /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml
checking with: ls /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml
/home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml
File /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/fabric-ca-client-config.yaml found.
======Completed: Step 1 : Copy Check Orderer Client YAML==========
###################################
# Enrolling: orderer
###################################
enrolling :=> fabric-ca-client enroll -u http://orderer-node:pw@192.168.1.10:7054
2019/10/16 17:26:28 [INFO] generating key: &{A:ecdsa S:256}
2019/10/16 17:26:28 [INFO] encoded CSR
Error: Response from server: Error Code: 20 - Authentication failure

======Completed: Step 2 : Enrolled orderer ========
###################################
# Setting up admincerts
###################################
DEBUG-ONLY: /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node == /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node ???
Creating /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts
====> /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts
Copying [/home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/signcerts] from host [msp-admin-orderer] here at [/home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts]
Getting orderer-admin certs with SCP
scp msp-admin-orderer:/home/ubuntu/hyperledger_ws/ca-client/orderer/admin/msp/signcerts/* /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts
The authenticity of host '192.168.1.13 (192.168.1.13)' can't be established.
ECDSA key fingerprint is SHA256:gUBm/m2JTOsExZpRVjVNwbjjxuegl/dmTMsf4kuPxJ4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.13' (ECDSA) to the list of known hosts.
cert.pem                                                                                                                                                                                                     100% 1021     1.0KB/s   00:00
Checking with: ls /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts/
cert.pem
File(s) found at /home/ubuntu/hyperledger_ws/ca-client/orderer/orderer-node/msp/admincerts/.
======Completed: Step 3 : MSP setup for the orderer ========
ubuntu@orderer-node:~/hyperledger_ws/setup_scripts$






ubuntu@orderer-node:~/hyperledger_ws/setup_scripts$ ./10_start_orderer.sh
FABRIC_CFG_PATH: /home/ubuntu/hyperledger_ws/fabric
/var/ledgers does not exist, creating it
/home/ubuntu/hyperledger_ws/fabric does not exist, creating it
/home/ubuntu/hyperledger_ws/fabric/configtx.yaml not found. copying from /home/ubuntu/hyperledger_ws/config_files
/home/ubuntu/hyperledger_ws/fabric/orderer.yaml not found. copying from /home/ubuntu/hyperledger_ws/config_files
/home/ubuntu/hyperledger_ws/fabric/core.yaml not found. copying from /home/ubuntu/hyperledger_ws/config_files
#######################################################################
getting GENESIS_BLK_NAME from orderer admin using scp
scp ubuntu@msp-admin-orderer:/home/ubuntu/hyperledger_ws/fabric/my_genesis.block /home/ubuntu/hyperledger_ws/fabric
my_genesis.block                                                                                                                                                                                             100% 8098     7.9KB/s   00:00
my_genesis.block
file my_genesis.block found at /home/ubuntu/hyperledger_ws/fabric
===> Done. Please check logs under /home/ubuntu/hyperledger_ws/fabric/orderer.log
ubuntu@orderer-node:~/hyperledger_ws/setup_scripts$
